
INSERT INTO SIEBEL.S_RESP (ROW_ID, CONFLICT_ID, CREATED_BY, LAST_UPD_BY, DB_LAST_UPD, DB_LAST_UPD_SRC, DCKING_NUM, MODIFICATION_NUM, BU_ID, NAME, ACCSS_TYPE_CD, DESC_TEXT, INTEGRATION_ID)
VALUES (siebel.s_sequence_pkg.get_next_rowid, '0', 'ScriptAuditMDM', '0-1', sysdate, 'ScriptAuditMDM', 0, 0, '0-R9NH', 'Data Security Auditor',NULL,'Аудитор информационной безопасности', NULL);


COMMIT;


INSERT INTO SIEBEL.S_APP_VIEW (ROW_ID, CONFLICT_ID, CREATED_BY, LAST_UPD_BY, DB_LAST_UPD, DB_LAST_UPD_SRC, DCKING_NUM, MODIFICATION_NUM, NAME, DESC_TEXT, EFF_END_DT, EFF_START_DT, LOCAL_ACCESS_FLG, CS_PATH_ID, VIS_COND_EXPR)
VALUES (siebel.s_sequence_pkg.get_next_rowid, '0', 'ScriptAuditMDM', '0-1', sysdate, 'ScriptAuditMDM', 0, 0, 'MDM Audit Screen List View', NULL,NULL,NULL,'Y',NULL,NULL);


COMMIT;


INSERT INTO SIEBEL.S_APP_VIEW (ROW_ID, CONFLICT_ID, CREATED_BY, LAST_UPD_BY, DB_LAST_UPD, DB_LAST_UPD_SRC, DCKING_NUM, MODIFICATION_NUM, NAME, DESC_TEXT, EFF_END_DT, EFF_START_DT, LOCAL_ACCESS_FLG, CS_PATH_ID, VIS_COND_EXPR)
VALUES (siebel.s_sequence_pkg.get_next_rowid, '0', 'ScriptAuditMDM', '0-1', sysdate, 'ScriptAuditMDM', 0, 0, 'MDM Audit Print/Export View', NULL,NULL,NULL,'Y',NULL,NULL);


COMMIT;


INSERT INTO SIEBEL.S_APP_VIEW_RESP (ROW_ID, CONFLICT_ID, CREATED_BY, LAST_UPD_BY, DB_LAST_UPD, DB_LAST_UPD_SRC, DCKING_NUM, MODIFICATION_NUM, LOCAL_ACCESS_FLG, READ_ONLY_FLG, RESP_ID, VIEW_ID)
VALUES (siebel.s_sequence_pkg.get_next_rowid, '0', 'ScriptAuditMDM', '0-1', sysdate, 'ScriptAuditMDM', 0, 0,'Y', 'N', (SELECT ROW_ID FROM SIEBEL.S_RESP WHERE NAME = 'MDM Developer'),(SELECT ROW_ID FROM SIEBEL.S_APP_VIEW WHERE NAME = 'MDM Audit Screen List View'));


COMMIT;


INSERT INTO SIEBEL.S_APP_VIEW_RESP (ROW_ID, CONFLICT_ID, CREATED_BY, LAST_UPD_BY, DB_LAST_UPD, DB_LAST_UPD_SRC, DCKING_NUM, MODIFICATION_NUM, LOCAL_ACCESS_FLG, READ_ONLY_FLG, RESP_ID, VIEW_ID)
VALUES (siebel.s_sequence_pkg.get_next_rowid, '0', 'ScriptAuditMDM', '0-1', sysdate, 'ScriptAuditMDM', 0, 0,'Y', 'N', (SELECT ROW_ID FROM SIEBEL.S_RESP WHERE NAME = 'Data Security Auditor'),(SELECT ROW_ID FROM SIEBEL.S_APP_VIEW WHERE NAME = 'MDM Audit Print/Export View'));


COMMIT;